package matchcomputer

sealed trait Message
case object MinRegisterValueMustBeLessOrEqualMaxRegisterValue extends Message
case object RegisterValueMustNotBeSmallerThanMinRegisterValue extends Message
case object RegisterValueMustNotBeGreaterThanMaxRegisterValue extends Message
case object IllegalAccessToNonexistingRegisterNumber extends Message
case object IllegalReferenceToNonexistingLinenumber extends Message
case object NoNextLinenumberFoundInProgram extends Message
case object MessageDuringUnitTests extends Message
